version: '2'
services:
  web:
    build: .
    volumes:
     - ./web:/usr/share/nginx/html
    ports:
     - "8080:80"
    environment:
      PORT: 80

  node:
    build: docker/node
    command: gulp
    volumes:
     - .:/src

