version: '2'
services:
  web:
    build: .
    volumes:
     - ./web:/usr/share/nginx/html
    ports:
     - "8080:80"
    environment:
      PORT: 80

  node:
    image: node:carbon
    working_dir: /app
    environment:
      - NODE_ENV=develop
    volumes:
     - .:/app
    command: "./docker/node/gulp-start.sh"

